const PRIMARY = '#766AF5';
const SECOND = '#DB2777';
const MUTED = '#656C86';
const HAIR = '#E6EAF4';
const NEUTRAL = '#CED3E3'; // 'no rating' / 'new' bars, visible on white
const $ = (id) => document.getElementById(id);
// value of a .seg toggle group = data-v of its pressed button
const segVal = (id) => $(id).querySelector('[aria-pressed="true"]').dataset.v;
function onSeg(id, fn) {
  $(id).addEventListener('click', (e) => {
    const b = e.target.closest('button');
    if (!b) return;
    $(id).querySelectorAll('button').forEach((x) => x.setAttribute('aria-pressed', x === b));
    fn();
  });
}

Chart.register(ChartDataLabels);
Chart.defaults.font.family = "'IBM Plex Sans', sans-serif";
Chart.defaults.color = MUTED;
Chart.defaults.plugins.legend.display = false;
Chart.defaults.datasets.bar.categoryPercentage = 0.62;
Chart.defaults.datasets.bar.barPercentage = 0.72;
if (matchMedia('(prefers-reduced-motion: reduce)').matches) Chart.defaults.animation = false;

const io = new IntersectionObserver((es) => es.forEach((e) => e.isIntersecting && (e.target.classList.add('is-in'), io.unobserve(e.target))), { threshold: 0.12 });
document.querySelectorAll('.reveal').forEach((el) => io.observe(el));

// data.json is generated by build_data.py
fetch('data.json')
  .then((r) => {
    if (!r.ok) throw new Error(r.status);
    return r.json();
  })
  .then(start)
  .catch((err) => {
    $('ptitle').textContent = 'Could not load data.json';
    $('empty').hidden = false;
    $('empty').textContent = `Error: ${err.message}. Open this page through a web server (GitHub Pages, or "python3 -m http.server" in the repo root), not straight from disk.`;
  });

function start({ players: ALL, year: YEAR, cats: CATS, min: MIN }) {
  document.querySelectorAll('.year').forEach((e) => (e.textContent = YEAR));
  document.querySelectorAll('.min').forEach((e) => (e.textContent = MIN));
  $('rated').options[1].textContent = `Rated (≥${MIN})`;

  const fide = (id) => 'https://ratings.fide.com/profile/' + encodeURIComponent(id);
  // rating format picked in the filter bar; 'best' = highest of the three
  const FORMATS = {
    best: ['in any format', (p) => Math.max(p.std || 0, p.rapid || 0, p.blitz || 0)],
    std: ['in standard', (p) => p.std || 0],
    rapid: ['in rapid', (p) => p.rapid || 0],
    blitz: ['in blitz', (p) => p.blitz || 0],
  };
  const rating = (p) => FORMATS[segVal('fmt')][1](p);
  const rated = (p) => rating(p) >= MIN;
  const fmt = (v) => (typeof v === 'number' ? v.toLocaleString() : v);
  const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]);
  const years = (n, i) => {
    const lo = YEAR - n, hi = i ? YEAR - CATS[i - 1] - 1 : null;
    return hi === null ? lo + '+' : lo === hi ? '' + lo : lo + '–' + hi;
  };
  const labels = CATS.map((n) => 'U' + n);
  const grid = { color: HAIR, drawTicks: false };
  const axes = () => ({
    x: { grid: { display: false } },
    y: { beginAtZero: true, grid, border: { display: false }, ticks: { padding: 8 } },
  });

  function stats(list) {
    const c = { Total: list.length, Boys: 0, Girls: 0, Rated: 0, 'Rated boys': 0, 'Rated girls': 0, 'No rating': 0 };
    for (const p of list) {
      const f = p.sex === 'F';
      c[f ? 'Girls' : 'Boys']++;
      if (rated(p)) {
        c.Rated++;
        c[f ? 'Rated girls' : 'Rated boys']++;
      } else c['No rating']++;
    }
    return c;
  }
  const byCat = (list) => CATS.map((n) => list.filter((p) => p.cat === n));

  // ---- summary table (all players, both sexes; follows the rating format) ----
  const summary = () => [
    ...byCat(ALL).map((l, i) => ({ Category: labels[i], 'Birth years': years(CATS[i], i), ...stats(l) })),
    { Category: 'Total', 'Birth years': '', ...stats(ALL) },
  ];
  const tr = (r) => '<tr>' + Object.values(r).map((v, i) => `<td${i > 1 ? ' class="num"' : ''}>${fmt(v)}</td>`).join('') + '</tr>';
  const sumBody = document.querySelector('#summary tbody');
  function renderSummary() {
    const rows = summary();
    sumBody.innerHTML = rows.slice(0, -1).map(tr).join('');
    document.querySelector('#summary tfoot').innerHTML = tr(rows.at(-1));
  }

  // ---- charts ----
  const pickCat = (i) => {
    $('cat').value = CATS[i];
    fresh();
    $('players-sec').scrollIntoView({ behavior: 'smooth' });
  };
  const onBar = (_, els) => els.length && pickCat(els[0].index);
  // value on each bar; skipped on narrow screens where grouped labels collide (tooltip still has them)
  const barLabels = { display: (c) => !!c.dataset.data[c.dataIndex] && c.chart.width > 520, anchor: 'end', align: 'end', color: MUTED, font: { size: 10, weight: '500' }, formatter: fmt };

  const catChart = new Chart($('catChart'), {
    type: 'bar',
    data: { labels, datasets: [
      { label: 'Boys', backgroundColor: PRIMARY, data: [] },
      { label: 'Girls', backgroundColor: SECOND, data: [] },
    ] },
    options: {
      maintainAspectRatio: false, onClick: onBar, scales: axes(), layout: { padding: { top: 20 } },
      plugins: { datalabels: barLabels },
    },
  });

  const ratedChart = new Chart($('ratedChart'), {
    type: 'bar',
    data: { labels, datasets: [
      { label: 'Rated', backgroundColor: PRIMARY, data: [] },
      { label: 'No rating', backgroundColor: NEUTRAL, data: [] },
    ] },
    options: {
      maintainAspectRatio: false, onClick: onBar, scales: axes(), layout: { padding: { top: 20 } },
      plugins: {
        datalabels: barLabels,
        tooltip: { callbacks: { footer: (items) => { const d = items[0].chart.data.datasets, i = items[0].dataIndex, n = d[0].data[i] + d[1].data[i]; return n ? Math.round((100 * d[0].data[i]) / n) + '% rated' : ''; } } },
      },
    },
  });

  const distChart = new Chart($('distChart'), {
    type: 'bar',
    data: { labels: [], datasets: [{ label: 'Players', backgroundColor: PRIMARY, data: [] }] },
    options: {
      maintainAspectRatio: false, scales: axes(), layout: { padding: { top: 20 } },
      plugins: { datalabels: { display: true, anchor: 'end', align: 'end', color: MUTED, font: { size: 10, weight: '500' } } },
    },
  });

  function renderCharts() {
    const sex = segVal('sex');
    const list = ALL.filter((p) => !sex || p.sex === sex);
    const groups = byCat(list);

    catChart.data.datasets[0].data = groups.map((l) => l.filter((p) => p.sex !== 'F').length);
    catChart.data.datasets[1].data = groups.map((l) => l.filter((p) => p.sex === 'F').length);
    catChart.data.datasets[0].hidden = sex === 'F';
    catChart.data.datasets[1].hidden = sex === 'M';
    catChart.update();
    document.querySelectorAll('.legend-item[data-sex]').forEach((el) => (el.hidden = !!sex && el.dataset.sex !== sex));

    ratedChart.data.datasets[0].data = groups.map((l) => l.filter(rated).length);
    ratedChart.data.datasets[1].data = groups.map((l) => l.filter((p) => !rated(p)).length);
    ratedChart.update();

    const bands = {};
    for (const p of list.filter(rated)) {
      const b = Math.floor(rating(p) / 100) * 100;
      bands[b] = (bands[b] || 0) + 1;
    }
    const keys = Object.keys(bands).map(Number).sort((a, b) => a - b);
    distChart.data.labels = keys.map((k) => `${k}–${k + 99}`);
    distChart.data.datasets[0].data = keys.map((k) => bands[k]);
    distChart.data.datasets[0].backgroundColor = sex === 'F' ? SECOND : PRIMARY;
    distChart.update();

    // scoreboard + insights follow the filter
    const s = stats(list);
    const biggest = groups.reduce((m, l, i) => (l.length > groups[m].length ? i : m), 0);
    const top = list.reduce((m, p) => (!m || rating(p) > rating(m) ? p : m), null);
    const inFmt = FORMATS[segVal('fmt')][0];
    document.querySelectorAll('.fmtname').forEach((e) => (e.textContent = inFmt));
    const who = sex === 'F' ? 'girls' : sex === 'M' ? 'boys' : 'youth players';
    $('scoreboard').innerHTML = [
      [fmt(s.Total), `NEP ${who} on the FIDE list`],
      [fmt(s.Rated), `rated ${MIN}+ ${inFmt}`],
      [sex ? Math.round((100 * s.Total) / ALL.length) + '%' : fmt(s.Girls), sex ? 'of all youth players' : 'girls'],
      [top && rating(top) ? rating(top) : '–', top && rating(top) ? `top rating ${inFmt}, ${esc(top.name)} (U${top.cat})` : 'top rating'],
    ].map(([n, l]) => `<div class="stat"><div class="stat-num">${n}</div><div class="stat-label">${l}</div></div>`).join('');

    $('cat-insight').textContent = s.Total
      ? `${labels[biggest]} is the largest group with ${fmt(groups[biggest].length)} ${who}.` +
        (sex ? '' : ` Girls make up ${Math.round((100 * s.Girls) / s.Total)}% overall.`)
      : '';
    $('rated-insight').textContent = s.Total
      ? `${Math.round((100 * s.Rated) / s.Total)}% of ${who} hold a ${MIN}+ rating ${inFmt}; most of the rest are registered but have no rating yet.`
      : '';
  }

  // ---- player list ----
  $('cat').innerHTML += CATS.map((n) => `<option value="${n}">U${n}</option>`).join('');
  const STEP = 100; // rows shown per 'Show more' click; the page scrolls, no nested scroll box
  let shown = STEP;
  function renderPlayers() {
    const q = $('q').value.trim().toLowerCase(), sex = segVal('sex'), rt = $('rated').value;
    const cat = $('cat').value ? +$('cat').value : null;
    const list = ALL.filter((p) => (cat === null || p.cat === cat) && (!sex || p.sex === sex) &&
      (!rt || rated(p) === (rt === '1')) && (!q || p.name.toLowerCase().includes(q) || p.id.includes(q)))
      .sort((a, b) => a.cat - b.cat || rating(b) - rating(a)); // stable: ties keep name order
    $('ptitle').textContent = (cat === null ? 'All youth players' : `U${cat} players`) + ` (${list.length.toLocaleString()})`;
    document.querySelector('#players tbody').innerHTML = list.slice(0, shown).map((p, i) => {
      const a = (t) => `<a href="${fide(p.id)}" target="_blank" rel="noopener">${esc(t)}</a>`;
      return `<tr><td class="num">${i + 1}</td><td>U${p.cat}</td><td>${a(p.id)}</td><td>${a(p.name)}</td><td>${esc(p.sex)}</td><td class="num">${p.by}</td><td>${esc(p.title)}</td><td class="num">${p.std ?? ''}</td><td class="num">${p.rapid ?? ''}</td><td class="num">${p.blitz ?? ''}</td></tr>`;
    }).join('');
    $('empty').hidden = list.length > 0;
    $('more').hidden = list.length <= shown;
    $('more').textContent = `Show more (${Math.min(shown, list.length).toLocaleString()} of ${list.length.toLocaleString()} shown)`;
    [...sumBody.rows].forEach((r, i) => r.classList.toggle('sel', CATS[i] === cat));
  }
  sumBody.addEventListener('click', (e) => { const r = e.target.closest('tr'); if (r) pickCat(r.sectionRowIndex); });
  const fresh = () => { shown = STEP; renderPlayers(); };
  $('more').onclick = () => { shown += STEP; renderPlayers(); };
  $('q').oninput = fresh;
  $('cat').onchange = $('rated').onchange = fresh;
  onSeg('sex', () => { renderCharts(); fresh(); });
  onSeg('fmt', () => { renderCharts(); renderSummary(); fresh(); });
  $('reset').onclick = () => { for (const id of ['q', 'cat', 'rated']) $(id).value = ''; fresh(); };

  // ---- Excel export ----
  $('dl').onclick = () => {
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(summary()), 'Summary');
    for (const n of CATS) {
      const list = ALL.filter((p) => p.cat === n).map((p, i) => ({
        '#': i + 1, 'FIDE ID': p.id, Name: p.name, Sex: p.sex, 'Birth year': p.by, Title: p.title,
        Standard: p.std ?? '', Rapid: p.rapid ?? '', Blitz: p.blitz ?? '', [`Rated (≥${MIN} ${FORMATS[segVal('fmt')][0]})`]: rated(p) ? 'Yes' : 'No', 'FIDE profile': fide(p.id),
      }));
      const ws = XLSX.utils.json_to_sheet(list);
      list.forEach((_, i) => { const c = ws['K' + (i + 2)]; if (c) c.l = { Target: c.v }; }); // clickable profile column
      XLSX.utils.book_append_sheet(wb, ws, 'U' + n);
    }
    XLSX.writeFile(wb, `nepal_youth_categories_${YEAR}.xlsx`);
  };

  renderSummary();
  renderCharts();
  renderPlayers();
}
